apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: web
spec:
  selector:
    app: prometheus-deployment
  ports:
  - protocol: "TCP"
    port: 9090
    targetPort: 9090
  type: LoadBalancer
