apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana-deployment
    component: grafana
