global:
  scrape_interval:     3s

  external_labels:
      monitor: 'watcher-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
    - targets: ['flask:5000']

